name: lint-free
on: [push, pull_request]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # repeat same job for each subsystem in the following subdirectories
        subdir: [web-app, machine-learning-client]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9" # update version(s) as needed
      - name: Install dependencies
        if: ${{ hashFiles(format('{0}/**/*.py', matrix.subdir)) != '' }}
        run: |
          cd ${{ matrix.subdir }}
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with pylint
        if: ${{ hashFiles(format('{0}/**/*.py', matrix.subdir)) != '' }}
        # you may set pylint to ignore any files or dependencies that make no sense to lint
        run: |
          cd ${{ matrix.subdir }}
          pylint_score=$(python -m pylint **/*.py | tee /dev/tty | sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p')
          echo "Pylint score was $pylint_score"
          if (( $(echo "$pylint_score < 9.5" | bc -l) )); then
            echo "Pylint score below 9.5, failing the lint job."
            exit 1
          fi
      - name: Format with black
        if: ${{ hashFiles(format('{0}/**/*.py', matrix.subdir)) != '' }}
        # you may set black to ignore any files or dependencies that make no sense to format
        run: |
          cd ${{ matrix.subdir }}
          python -m black --diff --check .
